"""Pydantic schemas for the passive trace-ingestion contract.

External producers write ``events.jsonl`` and ``meta.json``; RunoGraph parses
those files into these schemas and stores them through ``models.py``. The
service does not execute agents, tests, or graders. In particular, ``outcome``
is a caller-provided label rather than a verdict generated by RunoGraph.

Aliases use camelCase so the JSON wire format matches the React consumer
pattern used across the /api/v1 surface.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from typing import Annotated, Literal

from pydantic import (
    AfterValidator,
    BaseModel,
    Field,
    StringConstraints,
    field_validator,
    model_validator,
)

EventType = Literal[
    "file_read",
    "file_edit",
    "test_run",
    "tool_call",
    "error",
    "reflection",
    "final",
]

Outcome = Literal["running", "pass", "fail", "error"]
StoredOutcomeSource = Literal["external", "unknown"]
OutcomeLabelSource = Literal["external", "unknown", "mixed", "none"]
PUBLIC_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$"
_PUBLIC_ID_RE = re.compile(PUBLIC_ID_PATTERN)


def is_public_id(value: str) -> bool:
    """Whether a value is safe in URL path segments and comma scopes."""
    return _PUBLIC_ID_RE.fullmatch(value) is not None


def _validate_public_id(value: str) -> str:
    if not is_public_id(value):
        raise ValueError(
            "expected 1-128 ASCII letters, digits, '.', '_' or '-' with an "
            "alphanumeric first character"
        )
    return value


PublicId = Annotated[
    str,
    StringConstraints(
        min_length=1,
        max_length=128,
        strict=True,
    ),
    AfterValidator(_validate_public_id),
]
RunId = PublicId
TaskId = PublicId
ExperimentId = PublicId
NonNegativeInt = Annotated[int, Field(strict=True, ge=0)]
FiniteNonNegativeFloat = Annotated[
    float, Field(strict=True, ge=0, allow_inf_nan=False)
]
UnitInterval = Annotated[
    float, Field(strict=True, ge=0, le=1, allow_inf_nan=False)
]
NonEmptyText = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
def normalize_utc(value: datetime, field_name: str = "timestamp") -> datetime:
    """Require an offset-aware datetime and return its canonical UTC instant."""
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError(f"{field_name} must include a UTC offset")
    return value.astimezone(UTC)


def _validate_wire_datetime(value: object, field_name: str) -> object:
    """Reject Pydantic's numeric Unix-epoch coercion at the JSON boundary.

    Internal callers may still pass an already parsed ``datetime``. JSON has
    no datetime type, so an external producer must supply an ISO 8601 string.
    """
    if isinstance(value, datetime):
        return value
    if not isinstance(value, str):
        raise ValueError(
            f"{field_name} must be an ISO 8601 string with a UTC offset"
        )
    try:
        return datetime.fromisoformat(value)
    except ValueError as exc:
        raise ValueError(
            f"{field_name} must be an ISO 8601 string with a UTC offset"
        ) from exc


def normalize_outcome_source(value: object) -> StoredOutcomeSource:
    """Return a safe persisted provenance value for API/table output.

    Only the validated current ingest path can establish ``external``. Missing
    or unexpected legacy database values are conservatively reported as
    ``unknown``.
    """
    return "external" if value == "external" else "unknown"


class EventCost(BaseModel):
    tokens: NonNegativeInt
    time_seconds: FiniteNonNegativeFloat = Field(..., alias="timeSeconds")

    model_config = {"populate_by_name": True}


class CanonicalEvent(BaseModel):
    """One externally captured trace event in the canonical import shape."""

    event_id: NonEmptyText = Field(..., alias="eventId")
    timestamp: datetime
    type: EventType
    target: str | None = None
    content_summary: str | None = Field(None, alias="contentSummary")
    cost: EventCost
    parent_event_id: NonEmptyText | None = Field(None, alias="parentEventId")
    task_relevance_score: UnitInterval | None = Field(None, alias="taskRelevanceScore")

    @field_validator("timestamp", mode="before")
    @classmethod
    def _timestamp_has_wire_type(cls, value: object) -> object:
        return _validate_wire_datetime(value, "timestamp")

    @field_validator("timestamp")
    @classmethod
    def _timestamp_in_utc(cls, value: datetime) -> datetime:
        return normalize_utc(value)

    model_config = {"populate_by_name": True}


class RunMeta(BaseModel):
    """Run metadata supplied by the trace producer.

    ``outcomeSource`` is deliberately required and can only be ``external``.
    That makes every imported terminal outcome explicit about provenance and
    prevents the analysis service from appearing to verify a task itself.
    Token totals, cost, and timestamps are also imported measurements.
    """

    run_id: RunId = Field(..., alias="runId")
    task_id: TaskId = Field(..., alias="taskId")
    model: NonEmptyText
    started_at: datetime = Field(..., alias="startedAt")
    ended_at: datetime | None = Field(None, alias="endedAt")
    outcome: Outcome
    outcome_source: Literal["external"] = Field(..., alias="outcomeSource")
    total_tokens: NonNegativeInt = Field(..., alias="totalTokens")
    total_cost_usd: FiniteNonNegativeFloat = Field(..., alias="totalCostUsd")
    experiment_id: ExperimentId = Field(..., alias="experimentId")
    settings_hash: str | None = Field(None, alias="settingsHash")

    @field_validator("started_at", "ended_at", mode="before")
    @classmethod
    def _timestamps_have_wire_type(cls, value: object, info) -> object:
        if value is None and info.field_name == "ended_at":
            return value
        wire_name = "startedAt" if info.field_name == "started_at" else "endedAt"
        return _validate_wire_datetime(value, wire_name)

    @field_validator("started_at", "ended_at")
    @classmethod
    def _timestamps_in_utc(cls, value: datetime | None) -> datetime | None:
        return normalize_utc(value) if value is not None else None

    @model_validator(mode="after")
    def _chronology_is_valid(self) -> RunMeta:
        if self.ended_at is not None and self.ended_at < self.started_at:
            raise ValueError("endedAt must not precede startedAt")
        if self.outcome != "running" and self.ended_at is None:
            raise ValueError("endedAt is required for terminal outcomes")
        return self

    model_config = {"populate_by_name": True}


class RunSummary(BaseModel):
    """Compact run view with explicit persisted outcome provenance."""

    run_id: str = Field(..., alias="runId")
    task_id: str = Field(..., alias="taskId")
    model: str
    outcome: Outcome
    outcome_source: StoredOutcomeSource = Field(..., alias="outcomeSource")
    total_tokens: int = Field(..., alias="totalTokens")
    total_cost_usd: float = Field(..., alias="totalCostUsd")
    started_at: datetime = Field(..., alias="startedAt")
    ended_at: datetime | None = Field(None, alias="endedAt")
    experiment_id: str | None = Field(None, alias="experimentId")
    event_count: int = Field(0, alias="eventCount")

    model_config = {"populate_by_name": True}
